name: Deploy based on Tag

on:
  push:
    tags:
      - 'v*-stage'   # Тег для stage окружения
      - 'v*-prod'    # Тег для prod окружения

jobs:
  deploy:
    name: Deploy based on Tag
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout репозиторий
    - name: Checkout repository
      uses: actions/checkout@v2

    # Шаг 2: Настройка SSH-агента для подключения к серверу
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # Шаг 3: Определение окружения по тегу
    - name: Set environment
      id: set-env
      run: |
        if [[ "${GITHUB_REF}" == *-stage ]]; then
          echo "::set-output name=ENV::stage"
        elif [[ "${GITHUB_REF}" == *-prod ]]; then
          echo "::set-output name=prod"
        fi

    # Шаг 4: Копирование файлов на сервер
    - name: Copy files to server
      run: |
        scp -r -o StrictHostKeyChecking=no * ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/calories_bot

    # Шаг 5: Деплой на сервере с использованием переменных окружения из GitHub Secrets
    - name: Deploy on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /var/www/calories_bot
          
          # Определение имени контейнера в зависимости от окружения
          if [ "${{ steps.set-env.outputs.ENV }}" == "stage" ]; then
            CONTAINER_NAME=calories_bot_stage
          else
            CONTAINER_NAME=calories_bot
          fi
          
          # Удаление старого контейнера для текущего окружения
          docker rm -f $CONTAINER_NAME || true
          
          # Сборка нового контейнера
          docker build -t $CONTAINER_NAME .

          # Запуск нового контейнера с переменными из GitHub Secrets
          docker run -d --name $CONTAINER_NAME \
            -e OPENAI_API_KEY=${{ secrets[steps.set-env.outputs.ENV]_OPENAI_API_KEY }} \
            -e TELEGRAM_BOT_TOKEN=${{ secrets[steps.set-env.outputs.ENV]_TELEGRAM_BOT_TOKEN }} \
            -e PROVIDER_TOKEN=${{ secrets[steps.set-env.outputs.ENV]_PROVIDER_TOKEN }} \
            -e DATABASE=${{ secrets[steps.set-env.outputs.ENV]_DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e HOST=${{ secrets.SERVER_IP }} \
            -e LOG_ENV=${{ steps.set-env.outputs.ENV }} \
            -e RATE_LIMIT=${{ secrets[steps.set-env.outputs.ENV]_RATE_LIMIT }} \
            -e SECRET_WORD=${{ secrets.SECRET_WORD }} \
            -e GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }} \
            -e PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" \
            -e CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }} \
            -e CLIENT_ID=${{ secrets.CLIENT_ID }} \
            -e CERT_URL=${{ secrets.CERT_URL }} \
            -e PROJECT_ID=${{ secrets.PROJECT_ID }} \
            $CONTAINER_NAME
        EOF
