name: Deploy based on Tag

on:
  push:
    tags:
      - 'v*-stage'   # Тег для stage окружения
      - 'v*-prod'    # Тег для prod окружения

jobs:
  deploy:
    name: Deploy based on Tag
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout репозиторий
    - name: Checkout repository
      uses: actions/checkout@v2

    # Шаг 2: Настройка SSH-агента для подключения к серверу
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # Шаг 3: Определение окружения по тегу
    - name: Set environment
      id: set-env
      run: |
        if [[ "${GITHUB_REF}" == *-stage ]]; then
          echo "::set-output name=ENV::stage"
        elif [[ "${GITHUB_REF}" == *-prod ]]; then
          echo "::set-output name=ENV::prod"
        fi

    # Шаг 3.5: Удалиние и создание папки
    - name: Remove and create project directory on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          rm -rf /var/www/calories_bot &&
          mkdir -p /var/www/calories_bot
        "

    # Шаг 4: Копирование файлов на сервер
    - name: Copy files to server
      run: |
        scp -r -o StrictHostKeyChecking=no * ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/calories_bot

    # Шаг 5: Деплой на сервере с использованием переменных окружения из GitHub Secrets
    - name: Deploy on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /var/www/calories_bot
          
          # Определение имени контейнера в зависимости от окружения
          if [ "${{ steps.set-env.outputs.ENV }}" == "stage" ]; then
            CONTAINER_NAME=calories_bot_stage
            TELEGRAM_BOT_TOKEN=${{ secrets.STAGE_TELEGRAM_BOT_TOKEN }}
            PROVIDER_TOKEN=${{ secrets.STAGE_PROVIDER_TOKEN }}
            DATABASE=${{ secrets.STAGE_DB_NAME }}
            RATE_LIMIT=2
            LOG_ENV=stage
          else
            CONTAINER_NAME=calories_bot_prod
            TELEGRAM_BOT_TOKEN=${{ secrets.PROD_TELEGRAM_BOT_TOKEN }}
            PROVIDER_TOKEN=${{ secrets.PROD_PROVIDER_TOKEN }}
            DATABASE=${{ secrets.PROD_DB_NAME }}
            RATE_LIMIT=50
            LOG_ENV=prod
          fi
          
          # Удаление старого контейнера для текущего окружения
          docker rm -f $CONTAINER_NAME || true
          
          # Сборка нового контейнера
          docker build -t $CONTAINER_NAME .

          # Запуск нового контейнера с переменными
          docker run -d --name $CONTAINER_NAME \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
            -e PROVIDER_TOKEN=$PROVIDER_TOKEN \
            -e DATABASE=$DATABASE \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e HOST=${{ secrets.SERVER_IP }} \
            -e LOG_ENV=$LOG_ENV \
            -e RATE_LIMIT=$RATE_LIMIT \
            -e SECRET_WORD=${{ secrets.SECRET_WORD }} \
            -e GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }} \
            -e PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" \
            -e CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }} \
            -e CLIENT_ID=${{ secrets.CLIENT_ID }} \
            -e CERT_URL=${{ secrets.CERT_URL }} \
            -e PROJECT_ID=${{ secrets.PROJECT_ID }} \
            $CONTAINER_NAME
        EOF
